name = "papertrade"
main = "src/index.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "papertrade-db"
database_id = "ec653b18-39c7-4a87-abf4-94a3d68711ac"
